serviceConfig:
    scheme: https://
    hostName: fablix-idm.herokuapp.com
    port: 8080
    path: /api/idm

loggerConfig:
    outputDir: ./logs/
    outputFile: test.log

databaseConfig:
    dbUsername: bfd056424efd92
    dbPassword: 370bd420
    dbHostname: bfd056424efd92
    dbPort: 3306
    dbDriver: com.mysql.cj.jdbc.Driver
    dbName: heroku_e3f7fc48a1e5c29
    dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

sessionConfig:
    timeout: 600000
    expiration: 1800000